import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DashboardNav from "@/components/navbars/DashboardNav";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <div className="">

          {/* Sticky Navbar */}
          <div className="sticky top-0 z-50 pt-4 pb-4 bg-white shadow-md">
            <DashboardNav />
          </div>

          {/* Main Content */}
          <div>
            {children}
          </div>

        </div>
      </body>
    </html>
  );
}
